# Generated by Django 6.0.4 on 2026-05-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('niveau', models.CharField(choices=[('Débutant', 'Débutant'), ('Intermédiaire', 'Intermédiaire'), ('Avancé', 'Avancé')], max_length=20)),
                ('adresse', models.TextField()),
                ('objectif', models.CharField(choices=[('Je veux apprendre une nouvelle compétence', 'Je veux apprendre une nouvelle compétence'), ("Je veux apprendre le digital pour gagner de l'argent", "Je veux apprendre le digital pour gagner de l'argent"), ('Je veux améliorer mes compétences existantes', 'Je veux améliorer mes compétences existantes'), ('Je veux créer un business en ligne', 'Je veux créer un business en ligne')], max_length=100)),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
            },
        ),
    ]
