# Generated by Django 6.0.4 on 2026-05-06 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscription',
            options={'ordering': ['nom'], 'verbose_name': 'Inscription', 'verbose_name_plural': 'Inscriptions'},
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='prenom',
        ),
    ]
