# Generated by Django 5.1.8 on 2026-05-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_inscription_objectif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
