# Generated by Django 4.2.16 on 2026-05-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_inscription_objectif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='objectif',
            field=models.CharField(max_length=100),
        ),
    ]
